import type { Metadata } from "next";
import { Black_Han_Sans, Noto_Sans } from "next/font/google";
import "./globals.css";

const blackHanSans = Black_Han_Sans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-blackhan",
  style: "normal",
  display: "block",
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-notoSans",
  style: "normal",
});

// const pretendard = localFont({
//   src: "../fonts/pretendard/pretendardVariableSubset.woff2",
//   variable: "--font-pretendard",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${blackHanSans.variable} ${notoSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
